### ISSUE TITLE
Mushroom slider in ignore list

### ISSUE THREAD

**Issue by amaciuc** [zanna-37/hass-swipe-navigation#24]
Hi,

Can you implement this fix: [link](https://github.com/maykar/lovelace-swipe-navigation/pull/74) in your fork project? It prevents from swiping while changing light brightness with mushroom card.

**Comment by zanna-37** [comment]
Guys, this is super funny since it's [already there since ages](https://github.com/zanna-37/hass-swipe-navigation/blob/main/src/swipe-navigation.ts#L30). Are you sure you are using the correct repository?
Please uninstall other forks of this repo (or the original maykar's one) and _only_ install this one.

**Comment by amaciuc** [comment]
@zanna-37 oh, you are right. I double checked my frontend installations and I found a conflict.

thank you for your reply.
